GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/1

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Invalid blog",
    "author": "NotLoggedIn",
    "url": "www.example.com",
    "likes": 31
}

###
DELETE http://localhost:3001/api/blogs/6316d6d699410ed3afb2ef1c
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZFVzZXIiLCJpZCI6IjYzMTZkNTJmMTQyNWU0MjE2MzAyZDQwNiIsImlhdCI6MTY2MjQ0MTE0Nn0.qiRD2mjMR9XnA3z0DpjKgMbnJ0ioiyVPrxcsgSIJvXE


###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZFVzZXIiLCJpZCI6IjYzMTZkNTJmMTQyNWU0MjE2MzAyZDQwNiIsImlhdCI6MTY2MjQ0MTE0Nn0.qiRD2mjMR9XnA3z0DpjKgMbnJ0ioiyVPrxcsgSIJvXE

{
    "title": "Valid Blog",
    "author": "LoggedIn",
    "url": "www.example.com",
    "likes": 13
}