GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/1

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "TEST2",
    "author": "Ben",
    "url": "www.example.com",
    "likes": 3
}
